name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      # Public Firebase client vars required by lib/env.ts during build
      NEXT_PUBLIC_FIREBASE_API_KEY: ci-placeholder
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ci-placeholder.firebaseapp.com
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ci-placeholder
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ci-placeholder.appspot.com
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "1234567890"
      NEXT_PUBLIC_FIREBASE_APP_ID: 1:1234567890:web:abcdef0123456789
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-PLACEHOLDER
      NEXT_PUBLIC_FIREBASE_VAPID_KEY: BPLACEHOLDER
      # Avoid build failing on font download in CI
      NEXT_FONT_IGNORE_ERRORS: "1"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20.x'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run tests
      run: pnpm run test
    
    - name: Build application
      run: pnpm run build
