name: Dependency Review

on:
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-ghsas: GHSA-sample-ghsa-id
        deny-licenses: GPL-2.0, LGPL-2.0
        comment-summary-in-pr: true